# Generated by Django 6.0.4 on 2026-05-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0002_perfiladmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
    ]
