# Generated by Django 6.0.4 on 2026-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0003_remove_producto_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('Cliente', 'Cliente')], default='Cliente', max_length=20),
        ),
    ]
