# Generated by Django 6.0.4 on 2026-07-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0005_pago_monto_pago_referencia_alter_pago_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='es_domicilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='es_personalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='instrucciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucciones', models.TextField()),
                ('base', models.CharField(blank=True, max_length=100, null=True)),
                ('acompañamientos', models.TextField(blank=True, null=True)),
                ('salsas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalizado', to='Menud.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('fijo', 'Monto Fijo ($)')], default='porcentaje', max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='Menud.producto')),
            ],
        ),
    ]
