# Generated by Django 6.0.4 on 2026-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0006_pedido_direccion_entrega_pedido_es_domicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('base', 'Base/Proteína'), ('acompañamiento', 'Acompañamiento'), ('salsa', 'Salsa')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pedidopersonalizado',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
