# Generated by Django 6.0.4 on 2026-07-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0007_extra_pedidopersonalizado_precio_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Menud.pedido'),
        ),
    ]
