# Generated by Django 6.0.4 on 2026-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0009_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_ingredientes',
            field=models.BooleanField(default=True),
        ),
    ]
