# Generated by Django 6.0.4 on 2026-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0010_producto_tiene_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='ingredientes_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
