# Generated by Django 6.0.4 on 2026-08-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menud', '0011_detallepedido_ingredientes_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_mostrar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
