"""
Django settings for Sistema project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url  # <-- NUEVO: para usar DATABASE_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (solo para desarrollo local)
load_dotenv()

# --- Claves de API (DeepSeek, Stripe, Email) ---
# Es recomendable que todas estas claves las manejes con variables de entorno
# para no exponerlas en el código. Te dejo algunos ejemplos.
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY')
DEEPSEEK_API_URL = os.getenv('DEEPSEEK_API_URL')

# Stripe (mueve estas claves a variables de entorno en producción)
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_...')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_...')

# Email (mueve usuario y contraseña a variables de entorno)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'armandotoaquiza2000@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'fczm edob hxwi hikm')

# --- Seguridad y hosts ---
# SECURITY WARNING: keep the secret key used in production secret!
# Lee la clave secreta desde variable de entorno, o usa un valor por defecto solo para desarrollo
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure---z7)g!2)!8-55f)uhc3!9%etn7bn+9@-g++r8j^3b(jm+wgjq')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True en desarrollo, False en producción (por defecto False)
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS: se lee desde variable de entorno, separado por comas
# Ejemplo: 'miapp.onrender.com,www.midominio.com'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
# Si no se define, permitir localhost para desarrollo (opcional)
if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['']:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Para CSRF con dominios de Render y ngrok (en desarrollo)
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
]
# Añadir dinámicamente el dominio de Render si está definido en ALLOWED_HOSTS
for host in ALLOWED_HOSTS:
    if host.endswith('.onrender.com'):
        CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
        CSRF_TRUSTED_ORIGINS.append(f'http://{host}')  # por si acaso

# Configuración para proxy SSL (necesario si usas ngrok)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# En producción con Render, estas dos líneas son seguras, pero si usas HTTP local, desactívalas.
# Para que funcione tanto en local como en producción, puedes condicionarlas:
if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# --- Modelo de usuario personalizado ---
AUTH_USER_MODEL = 'Menud.Usuario'

# --- URLs de login/logout ---
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'menu'
LOGOUT_REDIRECT_URL = 'login'

# --- Configuración de correo (con variables de entorno) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'armandotoaquiza2000@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'fczm edob hxwi hikm')

# --- Application definition ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'Aplicacion.Menud',
]

SITE_ID = 1

# --- Middleware (se agrega WhiteNoise) ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- NUEVO: justo después de Security
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sistema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sistema.wsgi.application'

# --- Base de datos (PostgreSQL) ---
# Render inyecta automáticamente DATABASE_URL, pero también podemos usar variable de entorno.
# Si estamos en local y no tenemos DATABASE_URL, usamos la configuración manual.
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Configuración para desarrollo local (postgresql local)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'menudVirtual_db',
            'USER': 'postgres',
            'PASSWORD': 'luisTg_17',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --- Internationalization ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# --- Static files (CSS, JavaScript, Images) ---
STATIC_URL = '/static/'
# Directorio donde se recopilarán los archivos estáticos para producción (usado por collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Directorios adicionales donde Django busca archivos estáticos (para desarrollo)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Sistema/static')]

# --- Almacenamiento de archivos estáticos (WhiteNoise) ---
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- Media files (archivos subidos por usuarios) ---
# En Render, el sistema de archivos es efímero. Para producción, se recomienda usar S3 o Cloudinary.
# Pero dejamos la configuración local para desarrollo.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Sistema/media')

# --- Default primary key field type ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Base URL para enlaces (ej. para ngrok) ---
# Puedes usar variable de entorno para definir la URL base en producción.
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')