"""
Django settings for Sistema project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os, ssl
import dj_database_url  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (solo para desarrollo local)
load_dotenv()

# --- Claves API (DeepSeek, Stripe, etc.) ---
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY')
DEEPSEEK_API_URL = os.getenv('DEEPSEEK_API_URL')

# --- Seguridad: SECRET_KEY y DEBUG desde variables de entorno ---
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure---z7)g!2)!8-55f)uhc3!9%etn7bn+9@-g++r8j^3b(jm+wgjq')
DEBUG = os.getenv('DEBUG', 'False') == 'True'  # Por defecto False en producción

# --- Hosts permitidos: desde variable de entorno o lista por defecto ---
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else ['*']
# Para producción, debes poner tu dominio de Render: 'tusistema.onrender.com'

# Para ngrok (solo desarrollo) - en producción no se usan
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
] if DEBUG else []  # Solo si DEBUG=True

# Para que funcione con proxy (como ngrok)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# --- Modelo de usuario personalizado ---
AUTH_USER_MODEL = 'Menud.Usuario'

# --- URLs de login/logout ---
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'menu'
LOGOUT_REDIRECT_URL = 'login'

# --- Email (SMTP) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'luistoaquiza108@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'dtxp fgzf tgjf hkjo')

# --- Application definition ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'Aplicacion.Menud',
    'cloudinary',
    'cloudinary_storage',
]

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUD_NAME'),
    'API_KEY': os.getenv('API_KEY'),
    'API_SECRET': os.getenv('API_SECRET'),
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

SITE_ID = 1

# --- Stripe ---
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_51TMHB455FOVHRRBJo8ZCwWKtgJbwBvGkoRsWvBieB8PU25540YlSMlpHxy4R7VFloDTCDH39R1tkzYU0TUPZ4Avs00OjaCooCp')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_51TMHB455FOVHRRBJsgqC2z1ZDGQlfCnhvWjygCUBLKGWxhh5wEWhUTdQEt7x5ZxpPpBb5rxBMFaBRL0mDpkaprbq00k8wNffJG')

# --- Middleware (con WhiteNoise para archivos estáticos) ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- NUEVO: justo después de Security
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sistema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sistema.wsgi.application'

# --- Base de datos: usa DATABASE_URL si existe, sino la configuración local ---
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv(
            'DATABASE_URL',
            'postgresql://postgres:luisTg_17@localhost:5432/menudVirtual_db'
        ),
        conn_max_age=600,
        ssl_require=False if DEBUG else True
    )
}

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internationalization ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# --- Static files (CSS, JavaScript, Images) ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Sistema/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # <--- NUEVO: para collectstatic


# --- Media files (archivos subidos por usuarios) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Sistema/media')  # <--- NUEVO: para archivos subidos

# --- Default primary key field type ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- URL base para el sitio (usado en plantillas) ---
BASE_URL = os.getenv('BASE_URL', 'https://ammonium-sliceable-sizzle.ngrok-free.dev')


# Configuración de correo con timeout
EMAIL_TIMEOUT = 60
try:
    ssl._create_default_https_context = ssl._create_unverified_context
except AttributeError:
    pass
os.environ['GUNICORN_TIMEOUT'] = '120'